version: "3"
networks:
  birdserver_default:
    external: true
services:
  proxy:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    container_name: birdproxy
    image: "birdproxy"
    ports:
      - 80:80
      - 2333:80
      - 443:443
    networks:
      - birdserver_default
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    container_name: certbot
    profiles:
      - certificate
        #    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
